name: Build & publish janusgraph-kafka
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: 'release'
    - name: Setup Java8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B -DskipTests package
    - name: Upload artifcats
      uses: actions/upload-artifact@v1
      with:
        name: janusgraph-kafka-0.1.0
        path: target/janusgraph-kafka-0.1.0-distribution.zip